Action batching
Lokiedu/libertysoil-site pull request #734
Opened 2016-12-25 19:26 UTC by voidxnull

Closes #663.

2017-01-29 21:34 UTC, artkravchenko approved these changes

2017-02-03 11:41 UTC, indeyets commented
I, actually, believe that this is an antipattern. Our current code is bad too.

The proper solution is using actions for high-level events instead of treating them as datastore-micromanagement tool.

for example: instead of shooting `addPostToRiver` + `subscribeToPost` we should dispatch single `createPost()` action, which would be handled in different reducers

same approach in other places.

`redux-batched-actions` is a way to limit impact of bad design, but it is not a way of fixing design

2017-02-03 11:44 UTC, indeyets requested changes
I made a comment outside of review. see https://github.com/Lokiedu/libertysoil-site/pull/734#issuecomment-277228136

2017-02-17 03:14 UTC, voidxnull commented
I'm going to refactor actions one at a time when there's an opportunity. This PR is not needed anymore.

2017-02-17 03:14 UTC, closed without merging